#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo 'Runing type check...'
pnpm exec nx affected -t typecheck --uncommitted
pnpm exec nx affected -t typecheck --untracked


# echo 'Runing format task...'
# pnpm exec nx format:check --uncommitted
# pnpm exec nx format:check --untracked
